### ISSUE TITLE
A conversation never moves up to the top of the list when someone replies.

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Talk-Api#113]
See the second half of the discussion here https://github.com/zooniverse/Panoptes-Front-End/issues/3627

**Comment by simoneduca** [comment]
The problem is that `updated_at` timestamp doesn't get updated when there's a new message in the thread, but has the same value as `created_at`.
![screen shot 2017-04-28 at 14 58 57](https://cloud.githubusercontent.com/assets/8989606/25531970/755202b2-2c23-11e7-9b3a-b55694d96ef3.png)

**Comment by marten** [comment]
@simoneduca Have you tried adding `touch: true` to the relation from Message to Conversation [here](https://github.com/zooniverse/Talk-Api/blob/master/app/models/message.rb#L5)? That should get ActiveRecord to set the `updated_at` to the current time everytime a Message gets created.

**Comment by simoneduca** [comment]
Thanks Marten. Would anything else need changing on top of that, specs, etc.? Also, how do I test the change before merging it?

**Comment by marten** [comment]
I think probably a test here: https://github.com/zooniverse/Talk-Api/blob/master/spec/services/message_service_spec.rb would not go amiss. Happy to Screenhero on it if you get lost.
