### ISSUE TITLE
[RFC] Talk and an Organization

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/talk-api#121]
Trying to wrap my head around what it'd take to implement Talk resources with an Organization.

It appears Talk resources have a `section: project-#{project.id}`.
- [Talk-Api/app/models/concerns/sectioned.rb](https://github.com/zooniverse/Talk-Api/blob/d9917117fb6497a47170d59fd41817d39087a72f/app/models/concerns/sectioned.rb)

I think when creating something, like a new Board, which requires section to be defined, it checks Panoptes that the section (let's say project-1234) has a valid project ID, though I'm not entirely sure how this is happening.

So Talk would have to be refactored to accept 'project-1234' OR 'organization-5678'.

**Comment by camallen** [comment]
The section component would be the something like the project specific one (note there is a global `zooniverse` one too). E.g. `section =  "organization-#{org.id}"` and if you keep that consistent then i'm pretty sure everything will work out of the box API side. You'll have to wire up the views to use those section contexts though.

**Comment by camallen** [comment]
closing for now - feel free to reopen if needed.
