### ISSUE TITLE
Translator role isn't recognised by the API

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Talk-Api#188]
Creating a new board and restricting it to read/write by the translator role gets a 422 response from the POST request, with the following response body: `error: "The property '#/boards/permissions/read' value "translator" did not match one of the following values: all, team, moderator, admin"`

**Comment by camallen** [comment]
Should have a fix out in #189 - a workaround now is to setup the board and edit the allowed roles to set what you want.

**Comment by eatyourgreens** [comment]
Cheers, I'll pass that on to Galaxy Zoo.

**Comment by mwalmsley** [comment]
Thanks guys, happy to wait for #189.

**Comment by camallen** [comment]
This is now deployed and live on the production talk API.

**Comment by mwalmsley** [comment]
Thanks Cam, works great.
