### ISSUE TITLE
Deleted messages are still flagged as unread

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/talk-api#211]
I've got an unread message, but it's from an account that's been deleted. Consequently, there doesn't seem to be any way I can remove this notification for an unread message that isn't in my inbox:
![Top bar of the web site, showing that I have 1 unread message (but I don't.)](https://user-images.githubusercontent.com/59547/86448737-17d1b580-bd0f-11ea-8d75-8d47edcca997.png)

**Comment by lcjohnso** [comment]
Resolved this issue by identifying the set of `conversation_id` linked to the deleted user, and set all `user_conversation` entries tied to these conversations as `is_unread = FALSE`.  32 entries were edited.
