### ISSUE TITLE
Suppress SignalException on SIGTERM (upgrade to Puma >4)

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/talk-api#223]
https://www.rubydoc.info/gems/puma/Puma%2FDSL:raise_exception_on_sigterm

**Comment by camallen** [comment]
We should try and address this by upgrading puma first, though that depends on relaxing a the https://github.com/zooniverse/Social/blob/cc32e716f1efc9d4bd8e7bf764562b84e88a5020/zooniverse_social.gemspec#L22 depency and bumping that gem first. 

then update the puma config in the local gemfile and `bundle update puma`
