### ISSUE TITLE
Bump actionview to > 5.2.4.2

### ISSUE THREAD

**Issue by wgranger** [zooniverse/talk-api#242]
The actionview gem needs to be updated to at least the version above. I can't get dependabot to open an automated bump, but more info about this is available [here](https://github.com/advisories/GHSA-cr3x-7m39-c6jq). This is a moderate vulnerability.

**Comment by yuenmichelle1** [comment]
This will be taken care of with Rails upgrades. Work is in process to get up to this point and higher.
