### ISSUE TITLE
Bump json to >= 2.3.0

### ISSUE THREAD

**Issue by wgranger** [zooniverse/talk-api#243]
Dependabot isn't opening an automated PR, but the json gem needs to be bumped. This is a moderate vulnerability, and more info is contained [here](https://github.com/advisories/GHSA-jphg-qwrw-7w9g)

**Comment by wgranger** [comment]
`bundle update json` won't resolve this. Running `gem dependency json` shows the following:

```
Gem json-1.8.6
  rake (>= 0, development)
  test-unit (~> 2.0, development)

Gem json-2.1.0
  rake (>= 0, development)
  test-unit (~> 2.0, development)

Gem json-2.2.0
  rake (>= 0, development)
  test-unit (~> 2.0, development)
```

Only `rake` is in the `Gemfile.lock`. Neither are in the `Gemfile`. Is this bump something that is best done with a Rails upgrade?

**Comment by camallen** [comment]
looks like one of the other gems has locked the max version you can install with, you'll have to bump the offending gem to free the lock on json gem. Looks like sdoc might be the offending gem, i don't think that is used tbh - might be best to remove that dependency in `Gemfile` and see if you can bump. https://github.com/zooniverse/talk-api/search?q=sdoc&unscoped_q=sdoc 

I thought bundler reports which gem is blocking the update as well?
