### ISSUE TITLE
Panoptes focuses

### ISSUE THREAD

**Issue by parrish** [zooniverse/Talk-Api#28]
Figure out exactly how focuses will behave as an ApiResource and how search will integrate.

Move panoptes id field to a non-pk field to allow the same id for both subjects and collections

**Comment by aweiksnar** [comment]
Do you think if instead of having focuses we embedded the images in the comment markdown with a link to the object, and perhaps unique styling, it would achieve the same effect for users? I'm trying to justify having them live outside of the comments themselves. Is it mainly to improve comment searchability?

**Comment by parrish** [comment]
Having the focus embedded makes sense from a data perspective.

If we modify the comment body based on the associated focus, that makes it editable to the user -- which means we'd have to restrict them editing that and try to keep the associated focus in sync with new markdown syntax.

What do you think?

**Comment by aweiksnar** [comment]
Yeah, maybe subject mentions with `^GZ123456` could just become the focuses, instead of links, and then if users want to link to a subject with text specifically they could just use markdowns anchor tags and fill in the id/url

**Comment by parrish** [comment]
To disambiguate, there are both focuses and mentions.

Focuses make the comment explicitly about the subject/collection. There's only one for a comment.

Mentions are a reference to something else.  There can be any number and they just setup a link to that thing.  e.g. "^S123" would create a link to subject 123, e.g. "[^S123](/subjects/123)".  I'm pretty sure marked has hooks for adding new syntax, maybe that's the best way to implement that?

**Comment by aweiksnar** [comment]
Ahh I think I might have misinterpreted focuses. So just to confirm: they're used to link comments to an object, nothing that changes how the comment itself gets rendered, just on what discussion it gets listed under.

**Comment by parrish** [comment]
Yep.  And to quickly create a link to the mentioned thing

**Comment by parrish** [comment]
Closed by 492c1a6a
