### ISSUE TITLE
Can roles be public or accessible to section admins?

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Talk-Api#38]
Right now doing `GET /roles?section=431-Edwardo's Test Project` with a user (id 130) that is an admin on that section gives a `401 Error: not allowed to index? this Role`. 

Assuming this is unintentional it looks like it could be fixed by referring to the policy scope for the RolesController in the same way as the [ConversationsController](https://github.com/zooniverse/Talk-Api/blob/e24de3c8404e153e063d2109bddb7c5b5d1243c3/app/controllers/conversations_controller.rb#L6). 

Though, to me, it'd also make sense for the roles to just be publicly visible.

**Comment by parrish** [comment]
Closed by 9f3e6f8
