### ISSUE TITLE
Search sorting

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Talk-Api#40]
Could searches have a param to sort them by a given metric? Creation time and relevance are the most useful.

**Comment by parrish** [comment]
It's currently sorted by rank (relevance).  It's already a pretty heavy index, so I'd like to avoid duplicating the whole thing to add a created_at index.  How about waiting for feedback on it?

**Comment by chrissnyder** [comment]
Yea, that sounds like a plan to me.

**Comment by parrish** [comment]
I think we're good to close this.  Happy to reevaluate further down the road.
