### ISSUE TITLE
Export Talk data to project owner and collaborators

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Talk-Api#47]
I've posted an issue at zooniverse/Panoptes-Front-End#1057 about being able to download an export of a project's Talk data, and @camallen noted I need to post it here too. This will be important for many projects, especially humanities projects.

**Comment by mschwamb** [comment]
Do you mean you want the entire Talk database or do you want the ability to get a download with the  subjects contained in specific user collection or marked with a hashtag? In the past I've asked for the latter, so I'd like to see that functionality in the future

**Comment by vrooje** [comment]
I think the full database is most useful to me for some things, and I agree being able to download specific search results etc. would be useful too. For now, if we had to choose, I'd prefer the whole thing. Maybe @vvh might have a preference too?

**Comment by parrish** [comment]
I'm of a mixed opinion.  Passing around sanitized backups of the database is one thing, but if there are use cases for more specific data exports then that's another.

So far, the only common data request for talk has been of the collection variety mentioned by Meg.  Collections live in Panoptes, so the request would be served from there.

If we have a concrete list of use cases for exporting talk data, then that would definitely help me on this.

**Comment by vrooje** [comment]
On GZ CANDELS we retired about 1/4 of the subjects early based on an analysis using subjects tagged with at least one of several hashtags. At the time I used the Talk search, saved the results as HTML and stripped the subject IDs out, then cross-matched with my metadata and manually removed duplicates. But if the search results had been much bigger or the search more complex this would have been untenable and I'd have needed a Talk export.

**Comment by VVH** [comment]
Some of the more subjective or interpretive tasks in the humanities generate conversations and hashtags on Talk can help researchers pinpoint areas of confusion; identify emerging trends around hashtag use and advice giving; and just generally get a sense of how the community forms over time. Amongst other things, it would be cool to have the data to recreate Rob's beautiful Talk graph for some of the Oroborous projects (you know, the one with all the beautiful dots). Something that spit out the public facing user ID, comments and favorites would be good.

**Comment by chrissnyder** [comment]
I'd much rather take the approach of throwing everything at the team via sanitized db backups, either exported to CSV or maybe just the raw PostgreSQL. If we do it piecemeal, there will always be use cases that fall outside any sort of custom data export we create.

If somebody came to us then and said they'd like more than what we collect in the db, then that's a very different discussion than "hey, i know you have this data, I just need it in a format that I can parse".

What we could do is provide a bunch of common scripts to get data out of the data exports, share those with everyone on the site and ask for people to contribute back. This is step 2, but worth keeping in mind.

**Comment by parrish** [comment]
I agree with @chrissnyder for the most part, but if we can identify a common set of exports, I'd be happy to automate it and stick a button somewhere.

We'd want to limit it to a single project/section -- global exports are just database backups.  There's also going to be a rate limit on this as well.  Probably once per day or week and restricted to admins.

There's a pretty natural grouping here too:

Tags:
  - name
  - section
  - user_id
  - comment_id
  - taggable_id
  - taggable_type ('Subject', 'Collection')

Conversations:
  - board_id
  - board_title
  - board_description
  - discussion_id
  - discussion_title
  - comment_id
  - comment_body
  - focus_id
  - focus_type ('Subject', 'Collection')
  - user_id
  - user_login

Denormalizing anything else like subject metadata or collection lists is definitely out of scope.  Those would be separate data requests from Panoptes.

**Comment by vrooje** [comment]
Along with the date of each comment I think those would encompass everything I can think of needing for a project. I wouldn't have a problem with limiting exports to once a week and making it project-owner only.

**Comment by chrissnyder** [comment]
Definitely agree on scoping it to a project/section. Agree to a point on denormalizing extra data. It's not fair to science teams to expect them to have a mental model of our internal systems when it comes to getting data out of their projects. But I think having a holistic view of "project data exports" is beyond the scope of this issue.

You'd have a better idea than I on how much this would hammer the DB, but giving this capability to the project owner seems right to me. I certainly don't want to have to manually export data, and would much rather let the teams get at the data as and when they need it, with reasonable rate limits.

**Comment by parrish** [comment]
> It's not fair to science teams to expect them to have a mental model of our internal systems when it comes to getting data out of their projects

To a point.  The data has to be represented somehow, so we ultimately have to share a mental model of some data structure and domain language.

I'm only going out of my way to exclude things like subjects and collections because they don't exist within Talk -- they're simply external references.

If somebody wants to correlate talk data to those things in any way beyond their references, they'll need to pull that data from a different data source.

**Comment by mschwamb** [comment]
Didn't @DarrenMcRoy interview/contact a bunch of science teams for the Talk survey done last October? I definitely gave feedback in that call about all the Talk  info I've asked @parrish to extract in the past that I would like to be able to get out of new Talk without having to bother anyone  Maybe other teams might have mentioned what they would want to get out of talk data?

**Comment by parrish** [comment]
Should be hitting the site shortly.

**Comment by mschwamb** [comment]
@parrish  I imagine I'm one of the few people that have asked you for project Talk exports recently. If it is helpful, is there a preferred place for feedback if you want my input on the output?

**Comment by parrish** [comment]
Feel free to open an issue on this repo
