### ISSUE TITLE
Discussion comment sorting in dev vs production

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Talk-Api#48]
I believe there may be some different sorting behaviors happening in dev vs production for the discussion.links.comments list of ids.

[client request for reference](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/talk/latest-comment-link.cjsx#L30) : goal there  is to grab the last comment id, and then get its index in the discussion.links.comments list to calculate which page its on. Working in dev currently, but not production

In dev the list of comments comes back in the default sort order, and in production the list matches the comments sort query

Is this expected behavior or perhaps there's another param I can specify to get them returned in the same order?

**Comment by parrish** [comment]
I'm not entirely sure that's the case.  In order for the linked comment id's to get sorted on the response, you'll need to pass a param for linked sorting:

e.g. https://talk-staging.zooniverse.org/discussions/36
`comments: ["100", "150", "151", "159", "174", "172", "176", "175", "173", "220", "226"]`

vs
https://talk-staging.zooniverse.org/discussions/36?sort_linked_comments=created_at
`comments: ["100", "150", "151", "159", "172", "173", "174", "175", "176", "220", "226"]`

The default sort order is just a natural sort.  So, it's possible that two different db's would be ordering them differently without a sort order specified.

**Comment by aweiksnar** [comment]
Ahhh thanks!! Yeah you're right I'm missing that `sort_linked_comments` param

**Comment by parrish** [comment]
Cool.  Yeah, it's a non-standard param, but it's kind of necessary for linked id's to be terribly useful.  I'd like to revisit this if/when we switch serializer implementations.
