### ISSUE TITLE
Comment focus_type param

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Talk-Api#49]
I'm doing some work on comment focuses and noticed that that this error is coming up
```
The property '#/comments' contains additional properties ["focus_type"] outside of the schema when none are allowed
```
when submitting a comment with a focus
```
POST https://talk-staging.zooniverse.org/comments
{
  "comments":
  {
    "user_id":"288433",
    "discussion_id":37,
    "body":"Testing focus",
    "focus_id":150,
    "focus_type":"Subject"
  }
}
```
Is this request formatting correct, or does focus_type need to be a permitted param?

**Comment by parrish** [comment]
Wow.  Yeah, I should've caught that before.

**Comment by aweiksnar** [comment]
Sweet thanks for the fix
