### ISSUE TITLE
Root api redirecting json requests

### ISSUE THREAD

**Issue by camallen** [zooniverse/Talk-Api#53]
@parrish Seems the redirect is happening for json requests too.

`curl -v -H "Accept:application/json" -H "Content-Type:application/json" https://talk-staging.zooniverse.org`

>
* Rebuilt URL to: https://talk-staging.zooniverse.org/
* Hostname was NOT found in DNS cache
*   Trying 54.210.202.45...
* Connected to talk-staging.zooniverse.org (54.210.202.45) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: OU=Domain Control Validated; OU=EssentialSSL Wildcard; CN=*.zooniverse.org
* 	 start date: 2015-07-10 00:00:00 GMT
* 	 expire date: 2016-07-09 23:59:59 GMT
* 	 subjectAltName: talk-staging.zooniverse.org matched
* 	 issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
* 	 SSL certificate verify ok.
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: talk-staging.zooniverse.org
> Accept: application/json
> Content-Type:application/json
> 
< HTTP/1.1 302 Found
< Cache-Control: no-cache
< Content-Type: text/html; charset=utf-8
< Date: Wed, 29 Jul 2015 17:31:01 GMT
< Location: http://demo.zooniverse.org/panoptes-front-end/#/talk
* Server nginx/1.4.6 (Ubuntu) is not blacklisted
< Server: nginx/1.4.6 (Ubuntu)
< Strict-Transport-Security: max-age=31536000
< Strict-Transport-Security: max-age=31536000; includeSubdomains
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Request-Id: 83b09205-18ea-49e5-8303-2ace16c6074e
< X-Runtime: 0.008981
< X-XSS-Protection: 1; mode=block
< Content-Length: 118
< Connection: keep-alive
< 
* Connection #0 to host talk-staging.zooniverse.org left intact
<html><body>You are being <a href="http://demo.zooniverse.org/panoptes-front-end/#/talk">redirected</a>.</body></html>

**Comment by parrish** [comment]
@camallen Good catch.  Thanks!
