### ISSUE TITLE
Comment delete permissions

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Talk-Api#56]
@parrish I'm looking into https://github.com/zooniverse/Panoptes-Front-End/issues/1252 and am thinking that there may be a permissions mismatch between showing the moderations interface and deleting comments. Should anyone that has a role of admin or moderator be able to take actions from the moderations page? 

Right now I have it setup to show that page to admins and mods, and then iterate over the moderatable actions to set that row of buttons

**Comment by parrish** [comment]
Yep.  Looks like there's a case when the api is incorrectly denying show requests.  It's strange because the policy is allowing the action.  I'll look into it.

**Comment by aweiksnar** [comment]
Ok cool, Thanks

**Comment by parrish** [comment]
Okay, this should be fixed with 8d383c90d and 02acc27e.

I'll report back on the other issue after the deploy is out
