### ISSUE TITLE
Comment Replies

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Talk-Api#62]
Thoughts on adding reply functionality to comments? Mentioned in https://github.com/zooniverse/Panoptes-Front-End/issues/1434

**Comment by parrish** [comment]
I (mostly) liked the behavior of replies from the last talk, but it's a bit of an awkward thing to implement.

We either need to perform more api calls, use more sideloading, or have more denormalized attributes.  I don't have a clear picture of what's best in this case, so it might take some experimentation.

Are we shooting for the recursive reply-of-a-reply-of-a-reply thing again?

**Comment by parrish** [comment]
> We either need to perform more api calls, use more sideloading, or have more denormalized attributes.

@aweiksnar Comment responses are now including
  - reply_id - the id of the comment that was replied to
  - reply_user_<attr> - information about the user who wrote the comment being replied to
    - id
    - login
    - display_name

Basically, that gives us enough information to provide the comment link, the replied to user link (and avatar), and the "In response to <display_name>'s comment"

**Comment by aweiksnar** [comment]
Cool thanks for adding this in, I'll put something together for the frontend this week for this. Sorry I missed responding here earlier ; was in meetings through mid-day today
