### ISSUE TITLE
Failed Talk Tag Export from the Project builder. 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Talk-Api#64]
not sure if this is the correct place to post this. I requested a data dump of the talk tags export and I got back that it failed

**Comment by parrish** [comment]
Yep, that's my fault.  I forgot to upload the s3 configuration before deploying it.  It should be working now if you want to try again.  (I'll wait to close)

**Comment by mschwamb** [comment]
That worked. I have a separate small request, but I'll add that as a separate issue. Thanks @parrish
