### ISSUE TITLE
Ability to request the subject ids from a list of collections

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Talk-Api#65]
One thing that has come in handy in the past has been volunteer collections both for testing data analysis and especially for summer student projects. It would be nice with the Talk exports (or are collections a whole separate system?) to be able to give a list of collections either through file or write it in a text book  and get back a csv file for the subject ids associated with your project.

**Comment by parrish** [comment]
This is actually part of Panoptes now if you want to repost there.  This link to request them could be in the same section of the front end though
