### ISSUE TITLE
Adding length of time the link to the Talk data dump is active to the email with the link

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Talk-Api#67]
Right now it doesn't say how long the link is active for.  I think it would be good if could explicitly mention how long you have to access it it in the email with the data dump link. That info is  listed in the other data dump emails. It, and I've found it very handy.   

Edit - @parrish do let me know if I should move to the Frond end issues

**Comment by parrish** [comment]
Nope, this is good.  I'll add it tomorrow.

**Comment by parrish** [comment]
Closed by e5cf95dfd9e4655e7a99
