### ISSUE TITLE
Pictures are propagated into every following comment

### ISSUE THREAD

**Issue by m-a-j** [zooniverse/Talk-Api#75]
I've come from wildcamgongorosa, but I guess this is true for all zooniverse talk pages.

Whenever there's a photo linked to the first entry in a thread, it will also be linked/attached to every comment that is made there. Is this expected behavior? It's quite new. I don't speak Ruby, but maybe this was introduced with https://github.com/zooniverse/Talk-Api/commit/5108ad53f868cb96c77a38ab9350498aa6e54e5c ?

**Comment by parrish** [comment]
Yep, will have a fix out shortly.  You can follow the issue here: zooniverse/Panoptes-Front-End#1572
