### ISSUE TITLE
empty data exports

### ISSUE THREAD

**Issue by camallen** [zooniverse/Talk-Api#79]
Old weather exports are just empty array's after unzipping. Project_id: 1253, tried both tags and comments. Any ideas?

**Comment by parrish** [comment]
Looks like there aren't any tags or comments

**Comment by parrish** [comment]
Project 1253 has the slug zooniverse/oldweather.

Project 28 has the slug zooniverse/old-weather.

Project 28 is the one used by the front end.  Generating data exports seems to work fine for it too.
