### ISSUE TITLE
Talk exports expire too fast

### ISSUE THREAD

**Issue by philip-brohan** [zooniverse/Talk-Api#80]
I'm trying to download a batch of talk tags and comments for oldWeather (project 28) that I generated earlier today.
If I go to https://www.zooniverse.org/lab/28/data-exports there is a message saying " JSON format. Most recent data available requested 7 hours ago: Download. Available until Tomorrow at 3:35 PM." and the button to regenerate them is greyed out.
![screen shot 2015-12-17 at 22 05 45](https://cloud.githubusercontent.com/assets/2347784/11883447/f2b36558-a50a-11e5-8e91-f65babcc0c2f.png)
But if I click the download link I get a message that the token has expired
![screen shot 2015-12-17 at 22 06 07](https://cloud.githubusercontent.com/assets/2347784/11883463/06da94d4-a50b-11e5-9755-61d99e985b81.png)
So I can neither download the data, nor regenerate it.

**Comment by astopy** [comment]
There was a similar issue in Panoptes; I suspect this is being caused by the same thing. By default it will be generating the signed URL with the AWS keys from the EC2 instance's IAM role, but those keys get rotated/expire pretty frequently. Talk will need to use a fixed key from an IAM user instead, which is what we did in Panoptes.

**Comment by astopy** [comment]
@parrish I've added access_key_id and secret_access_key to aws.yml for both staging and production. Do we need any code changes to make it use those? If I understand [the code](https://github.com/zooniverse/Talk-Api/blob/master/lib/uploader.rb#L15) correctly, it should just pick that up after the next deploy, right?

**Comment by parrish** [comment]
That should do it.  Good job tracking that down!

I'm triggering a deploy to see if this fixes it

**Comment by parrish** [comment]
@philip-brohan This should be deployed now if you want to try it again.  Please reopen this if it becomes an issue again
