### ISSUE TITLE
Conversations' "users" link appears broken

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Talk-Api#91]
A conversation's link to its users comes back as `"/users?user_id={conversations.id}"`.

It looks like it should be `"/users?conversation_id={conversations.id}"`.

Neither return the expected results.

**Comment by parrish** [comment]
> `/users?user_id={conversations.id}`

Yeah, it looks like restpack got super confused by that association.

> It looks like it should be `/users?conversation_id={conversations.id}`

Talk doesn't actually support a users resource.  It only provides a search/autocomplete endpoint.  It's one of the quirks of maintaining separation between talk and panoptes.  Users fall on the panoptes side of the fence.  `/conversations?include=users` works as expected however.

I don't have a great solution to this, but I suppose the links to users could be excluded from the response.
