### ISSUE TITLE
Not currently possible to extract recent, non-Subject-based comments?

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Talk-Api#94]
I am trying to build a view which loads recent, text-only (i.e. not-based-upon-a-Subject) comments, ordered by recency, paginated.

I can use

https://talk-staging.zooniverse.org/comments?section=project-1611&focus_type=Subject

to get the inverse, but there seems to be no way to pick out the non-Subject comments, which are identified by `focus_id=""` or `focus_type=null`, neither of which seems to be possible to filter on.

For example, I want to retrieve comments 1035 & 1036 under
https://talk-staging.zooniverse.org/comments?section=project-1611

![screenshot 2016-08-04 11 05 56](https://cloud.githubusercontent.com/assets/1473244/17398827/b2e7d7ec-5a36-11e6-9136-ee5b2ef61427.png)

Perhaps a custom field could be added which has a non-null, non-empty string value, when `focus_id=""`, and that could be added to the list of filters here https://github.com/zooniverse/Talk-Api/blob/master/app/serializers/comment_serializer.rb#L9?

**Comment by marten** [comment]
I'd be more in favour of making sure `GET /comments?focus_type=&section=project-1611` works to filter on only empty/null focusses.

**Comment by parrish** [comment]
Comments are already filterable by focus_id.

This appears to be an issue with restpack.  @marten It also looks like the same behavior as panoptes.

With `?focus_id=`, the generated clause is `WHERE 1=0`.

With `?focus_id=null`, the generated clause is `WHERE "comments"."focus_id" = 0`.

Looks like more monkeypatching to support this. 😞

**Comment by parrish** [comment]
This is fixed on staging.  I'm going to make sure there weren't any unintended side effects before putting it into production.

**Comment by alexbfree** [comment]
Thanks @parrish ! So with your fix we will be able to filter on both null and empty string values for all fields in Talk Api?

**Comment by parrish** [comment]
Yep.  This is fixed now.

**Comment by alexbfree** [comment]
@parrish which is the PR that fixed this?

**Comment by parrish** [comment]
Here's a [diff](https://github.com/parrish/restpack_serializer/compare/0533163...f2b93bb) if you're curious...
