### ISSUE TITLE
Allow all notifications for particular section to be marked "read"

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Talk-Api#98]
Currently, all of a user's unread notifications can be marked read via the `/notifications/read` endpoint. However, it would be nice to filter this by a particular section, thus allowing all notifications for a particular project to be read. 

This would help since the new notifications page is divided by sections.

**Comment by parrish** [comment]
Added in 5a7c15f086

Deploy is on the way out now

**Comment by wgranger** [comment]
Oh nice. Thanks.
